export const createMockPrisma = () => {
  const mockPrisma = {
    user: {
      findUnique: jest.fn(),
      findFirst: jest.fn(),
      findMany: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
      updateMany: jest.fn(),
      delete: jest.fn(),
      deleteMany: jest.fn(),
      upsert: jest.fn(),
      count: jest.fn(),
    },
    club: {
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    team: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    player: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    match: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    matchPlayer: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    matchEvent: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    clubUser: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    teamUser: { 
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        updateMany: jest.fn(),
        delete: jest.fn(),       
        deleteMany: jest.fn(),
        upsert: jest.fn(),
        count: jest.fn(),
     },
    $transaction: jest.fn((callback) => callback(mockPrisma)),
  };
  return mockPrisma;
};